### ISSUE TITLE
add snapml solver

### ISSUE THREAD

**Issue by agramfort** [benchopt/benchmark_logreg_l2#24]
https://snapml.readthedocs.io/en/latest/logistic_regression.html

**Comment by agramfort** [comment]
@tanglef do you have any interest in giving this a try?

**Comment by tanglef** [comment]
I will soon do a "Benchopt day" and yes try and take care of this :)

**Comment by agramfort** [comment]
@tanglef do you have time to tackle this one also now?

**Comment by tanglef** [comment]
Yes. I was just waiting for us to settle things with logregL1 to do this one. (And I might give a look at the Cuml one. Deadline monday / tuesday 🙂)
